name: Test Backend

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # TODO: テストコマンドをここに追加してください
      - name: Exec test
        run: |
          echo "TODO: add test command"
